### ISSUE TITLE
Question to author regarding another project

### ISSUE THREAD

**Issue by 9Morello** [mnemesong/languages-test#1]
Hello! Sorry to create an issue in an unrelated repository.
I was wondering, do you still keep a repository for your `result-tools` library? It would be cool to be able to contribute to it.

I was running into a namespace colision with your `option-tools` library if I tried to use both together. Perhaps the helper class in `result-tools` could be called `ResultTools` instead of `OptionTools`?

Thanks in advance.

**Comment by mnemesong** [comment]
Hello. I have stopped support of this libraries after Bitbucket stop stupport repositories from RF. If you want, you may create analogue. For referense you may use https://rescript-lang.org/docs/manual/latest/api/belt/result - library from resript, case it well designed. 

If you will not, i may recreate this packages with another name and another repo. But now i will realize them as Enum

**Comment by 9Morello** [comment]
@mnemesong Hi, thanks for responding, I will likely publish a fork of it then. :) Thanks again
